### PR TITLE
Add Balance Druid Spell Hit Modifiers & Fix issue 129

### PR DESCRIPTION
**Pull request by Lenois**

### CODE REVIEW

**Comment by Lenois** [comment]
image

**Comment by Lenois** [comment]
I did test this locally with my character with all my hit gear off and it seems to work correctly.

**Comment by Lenois** [comment]
I also tested respeccing and making sure that the point award is correct at 0 and 1 talent point

**Comment by Lenois** [comment]
@BreakBB Do you have time to look at this?

**Comment by BreakBB** [comment]
Hey @Lenois thanks for this PR, I won't have time till next week to merge and release this.

But the PR looks good and I am very grateful for your help :+1:

**Comment by Lenois** [comment]
@BreakBB Awesome! Thanks for creating this awesome addon, glad I could help.

**Comment by Lenois** [comment]
I also added a fix for https://github.com/BreakBB/ExtendedCharacterStats/issues/129

**Comment by Lenois** [comment]
If you prefer I can revert it and merge the two separately.

**Comment by BreakBB** [comment]
Thank you very much @Lenois for this great PR 👍🏻 I will try to release this fix very soon.

**Pull request merged**
